//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Appointment_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public int Service_ID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string Status { get; set; }
        public int PaymentMethod_ID { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
