//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public int ReasonId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public int ComplaintsTypeId { get; set; }
        public int StatusID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual Review Review { get; set; }
        public virtual TargetType TargetType { get; set; }
        public virtual StatusesRequest StatusesRequest { get; set; }
    }
}
