//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmGenre
    {
        public int FilmGenreID { get; set; }
        public int FilmID { get; set; }
        public int GenreID { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
