//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSerive
    {
        public int MasterServ_ID { get; set; }
        public int User_ID { get; set; }
        public int Service_ID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }

    }
}
