//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingList
    {
        public int ReadingListsId { get; set; }
        public int UserId { get; set; }
        public int BookId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime AddedAt { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual StatusesReading StatusesReading { get; set; }
        public virtual User User { get; set; }
    }
}
