//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatsSession
    {
        public int SeatsSessionsID { get; set; }
        public int SeatID { get; set; }
        public int SessionID { get; set; }
    
        public virtual Seat Seat { get; set; }
        public virtual Session Session { get; set; }
    }
}
