//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShutAndKingEntities : DbContext
    {
        public ShutAndKingEntities()
            : base("name=ShutAndKingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthorRequest> AuthorRequests { get; set; }
        public virtual DbSet<BookGenre> BookGenres { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<ReadingList> ReadingLists { get; set; }
        public virtual DbSet<Reason> Reasons { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatusesReading> StatusesReadings { get; set; }
        public virtual DbSet<StatusesRequest> StatusesRequests { get; set; }
        public virtual DbSet<TargetType> TargetTypes { get; set; }
        public virtual DbSet<UnfreezeRequest> UnfreezeRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
