//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequest
    {
        public int RequestId { get; set; }
        public int UserId { get; set; }
        public int TargetTypeId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string Reason { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual StatusesRequest StatusesRequest { get; set; }
        public virtual TargetType TargetType { get; set; }
        public virtual User User { get; set; }
    }
}
