//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int ID_PurchaseOrder { get; set; }
        public int ID_ShopZapchast { get; set; }
        public int ID_Sklad { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int DeliveryProgress { get; set; }
        public string Status { get; set; }
    
        public virtual ShopZapchast ShopZapchast { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
