//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon
    {
        public int ID_Salon { get; set; }
        public string Name { get; set; }
        public double Money { get; set; }
        public double Nacenka { get; set; }
        public double PenaltyOtkaz { get; set; }
        public double PenaltyWrong { get; set; }
        public int CountClients { get; set; }
        public int SuccessfulRemont { get; set; }
        public int CountOtkaz { get; set; }
        public int CountFaild { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
