//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salon
    {
        public int ID_Salon { get; set; }
        public string Name { get; set; }
        public int ID_Sklad { get; set; }
        public double Money { get; set; }
        public int ID_Order { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
