//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int ID_Sklad { get; set; }
        public int ID_Zapchast { get; set; }
        public int Count { get; set; }
        public int InDelivery { get; set; }
        public int DeliveryProgress { get; set; }
    
        public virtual Zapchast Zapchast { get; set; }
    }
}
