//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_PogosyanHouse1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int ID_OrdHistory { get; set; }
        public int ID_Product { get; set; }
        public int ID_Order { get; set; }
        public int CountProduct { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
