//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Pogosyan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientQueue
    {
        public int ID_ClientQueue { get; set; }
        public int ID_Client { get; set; }
        public int ID_Zapchast { get; set; }
        public int Position { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Zapchast Zapchast { get; set; }
    }
}
