//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Pogosyan2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonEntities : DbContext
    {
        public SalonEntities()
            : base("name=SalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientQueue> ClientQueues { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Salon> Salons { get; set; }
        public virtual DbSet<Sklad> Sklads { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Zapchast> Zapchasts { get; set; }
    }
}
