//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP223_Pogosyan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID_Transaction { get; set; }
        public string TypeOperations { get; set; }
        public string Summa { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    }
}
